package com.mail.handler;

import java.io.IOException;
import java.util.List;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.web.authentication.SavedRequestAwareAuthenticationSuccessHandler;
import org.springframework.stereotype.Component;

@Component
public class SuccessRHnadler extends SavedRequestAwareAuthenticationSuccessHandler{

	@Override
	public void onAuthenticationSuccess(HttpServletRequest request, HttpServletResponse response,
			Authentication authentication) throws ServletException, IOException {
		
		String role = null;
		
		@SuppressWarnings("unchecked")
		List<GrantedAuthority> authorites = (List<GrantedAuthority>) authentication.getAuthorities();
      for(GrantedAuthority authority: authorites) {
    	  role = authority.getAuthority();
    	  
    	  if(role.equals("customer")) {
    		  response.sendRedirect("/autogeneratedmail/home.htm");
    	  }
    	  
    	  if(role.equals("admin")) {
    		  response.sendRedirect("/autogeneratedmail/admin-home.htm");
    	  }
      }
	}
}
